- nubis/Puppetfile
> Use our fork of puppet-varnish until it's fixed

- nubis/puppet/traefik.pp
> switch over to gozers fork of Traefik

- nubis/puppet/varnish.pp
> Expose varnish to service discovery

- nubis/puppet/traefik.pp
> Upgrade to Traefik v1.4.0-rc4

- nubis/Puppetfile
- nubis/puppet/ci.pp
> Upgrade jenkins to 2.73.2

- nubis/puppet/ci.pp
> Updating jenkins plugin

- nubis/puppet/varnish.pp
> Add varnish exporter

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
> Expose prometheus metric

- nubis/puppet/traefik.pp
> Bump traefik to v1.4.4

- nubis/terraform/dns.tf
- nubis/terraform/dns/README.md
- nubis/terraform/dns/inputs.tf
- nubis/terraform/dns/main.tf
- nubis/terraform/dns/outputs.tf
- nubis/terraform/outputs.tf
Needs reviewing but leaving this PR here first, will fix issue #41
> [review]Add support for dns creation

- nubis/puppet/static.pp
This was removed by mistake in PR #47
> Add missing parameter that was removed accidently

- nubis/puppet/files/jenkins-startup
Otherwise, we'll just grow endlessly
Fixes #49 and #46 (dup)
> Run docker-cleanup to clean up docker images

- nubis/puppet/files/svc-traefik.json
> Use the new port for Traefik service discovery

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
- nubis/puppet/sites.pp
- nubis/terraform/sites.tf
- sites/getfirebug.groovy
> Add new static site: getfirebug

- nubis/Puppetfile
- nubis/puppet/ci.pp
> Use OpenJDK instead of Oracle Java

- nubis/puppet/files/svc-traefik.json
> Tag our Traefik service for metrics ingestion

- nubis/puppet/traefik.pp
Contains fix for containous/traefik#2738
Fixes #62
> Upgrade to Traefik v1.5.0

- nubis/puppet/sites.pp
- nubis/terraform/sites.tf
- sites/mozqa.groovy
- utils/test.pl
- utils/test.yaml
> Add mozqa.com

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
> Don't try and get a stage cert for events.mozspaces.org

- sites/firefoxux.groovy
See FirefoxUX/firefoxUX.github.io#15
Fixes #59
> The SharedBanner repo is gone

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
- nubis/puppet/sites.pp
- nubis/terraform/sites.tf
- sites/dynamicua.groovy
> Add dynamicua-origin.cdn.mozilla.net

- nubis/terraform/dns.tf
- nubis/terraform/dns/inputs.tf
- nubis/terraform/dns/main.tf
This came up after discussing the ccadb work in CAB. I'm certainly open to feedback on the change. We are moving ccadb to Haul soon and this change came up while discussing a potential rollback (in the unlikely case that something fails and we cannot resolve it).
> decrease NS TTL from 1 day to 1 hour

- nubis/Puppetfile
- nubis/builder/project.json
- nubis/puppet/ci.pp
- nubis/puppet/docker.pp
- nubis/puppet/files/confd/conf.d/traefik.toml
- nubis/puppet/files/docker-cleanup.systemd
- nubis/puppet/files/jenkins-startup
- nubis/puppet/files/traefik.systemd
- nubis/puppet/files/varnish_exporter.systemd
- nubis/puppet/traefik.pp
- nubis/puppet/varnish.pp
- nubis/terraform/consul.tf
- nubis/terraform/main.tf
> Upgrade to Nubis v2.1.0

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
> Provide a Traefik config comment from Consul so we can trigger a restart

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
- nubis/puppet/sites.pp
- nubis/terraform/sites.tf
- sites/planet-de.groovy
@limed Can you review my changes and merge please? Thanks!
> Adding planet.mozilla.de to Haul

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
- nubis/puppet/sites.pp
- nubis/terraform/sites.tf
Fixed the docroot issue, was using planet-mozilla-de, when it is actually planet-de
> Fixing docroot for planet.moz.de and stage

- nubis/puppet/sites.pp
This is a minor change. Once it is reviewed and merged, I can validate that it functions in stage before promoting to production.
> Bug 1442751: modifies x-frame-options header value

- nubis/puppet/logs.pp
> Fixing position file for traefik_error

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
- nubis/puppet/sites.pp
- sites/experiencethearch.groovy
- utils/sites.t
- utils/test.yaml
> Add experiencethearch

- nubis/terraform/sites.tf
- nubis/terraform/sites/main.tf
- nubis/terraform/sites/variables.tf
> Revert "adding CloudFront to Haul with tf module"

- nubis/terraform/sites.tf
- nubis/terraform/sites/main.tf
- nubis/terraform/sites/variables.tf
Submitting my work in progress.
> adds CloudFront module for the PublicSuffix site

- sites/tlscanary.groovy
See https://bugzilla.mozilla.org/show_bug.cgi?id=1473656
> [tlscanary] Update git repo to mozilla owned repo

- nubis/terraform/sites.tf
- nubis/terraform/sites/main.tf
- nubis/terraform/sites/variables.tf
> Revert "removing references to CloudFront module"

- sites/iot.groovy
Fixes #143
Fixes mozilla-itcloud/scl3-migration-project#23
> [iot] Add schemas repo

- nubis/puppet/files/redirects.conf
Added new redirects and reviewed all commits from October 2nd 2017 until the last one made on July 3rd 2018 to verify that all redirects are current and up to date with the conf in the data center.
> That was tedious 

- nubis/puppet/files/confd/templates/traefik.toml.tmpl
- nubis/puppet/sites.pp
This should fix #163. Several domains were missed in the migration.
> adding new virtualhosts for additional start domains

- nubis/terraform/main.tf
> Remove CI system from web tier ELB

- nubis/terraform/dns.tf
trying to fix issue 177 - hope I didn't screw things up.
> add mozilla.frl MX records issue 177
